#!/usr/bin/env bash
# this script displays to infinity and beyond indefinitely wiht a sleep 2 in between each iteration and I am invinceble when recieving a SIGTERM signal
while true
do
	trap "echo I am invincible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
			
done
