#!/usr/bin/env bash
#This is a script that diplays numbers 1 to 20 except for lines 4, 9, and 17, which display bas luck from China, bad luck from Japan and bad luck from Italy respectively
i=1
while [ "$i" -le 20 ]
do
	echo "$i"
	case "$i" in
		4) echo "bad luck from China"

		;;
		
		9) echo "bad luck from Japan"
		
		;;

		17) echo "bad luck from Italy"
		;;
	esac
	((i++))

done	
